name: Kralbet M3U Güncelleme

on:
  schedule:
    - cron: '0 12 * * *'  # Her gün saat 12:00 (UTC)
  workflow_dispatch:
  push:
    paths:
      - Pythonlar/kralbet.py

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları Kur
        run: |
          pip install requests beautifulsoup4
      - name: kralbet.py Scriptini Çalıştır
        run: python Pythonlar/kralbet.py

      - name: Değişiklikleri Commit Et ve Pushla
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add kralbet.m3u
          git commit -m "🔄 Otomatik m3u güncelleme" || echo "No changes"
          git push || echo "No changes to push"
